myapp/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

myapp/lunchmap/urls.py
from django.urls import path
from . import views

app_name = 'lunchmap'

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('<int:pk>/', views.DetailView.as_view(), name="detail"),
    path('create/', views.CreateView.as_view(), name="create"),
    path('<int:pk>/update/', views.UpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name="delete"),

]

myapp/myapp/urls.py

from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lunchmap/', include('lunchmap.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/lunchmap/')),
]

myapp/accounts/models.py
from django.db import models

# Create your models here.

myapp/lunchmap/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=255)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Shop(models.Model):
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('lunchmap:detail', kwargs={'pk': self.pk})

myapp/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

myapp/lunchmap/views.py
from django.views import  generic
from .models import Category, Shop
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied


class IndexView(generic.ListView):
    model = Shop


class DetailView(generic.DetailView):
    model = Shop


class CreateView(LoginRequiredMixin, generic.CreateView):
    model = Shop
    fields = ["name", "address", "category"]  #"__all__"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(CreateView, self).form_valid(form)


class UpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Shop
    fields = ["name", "address", "category"]  #"__all__"

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != self.request.user:
            raise PermissionDenied("You do not have permission to edit.")
        return super(UpdateView, self).dispatch(request, *args, **kwargs)


class DeleteView(LoginRequiredMixin, generic.edit.DeleteView):
    model = Shop
    success_url = reverse_lazy('lunchmap:index')

myapp/accounts/templates/accounts/signup.html
{% extends 'layout.html' %}

{% block content %}
<h1>Sign up</h1>
<section class='common-form'>
    <form method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type='submit'>Sign up</button>
    </form>
</section>
{% endblock %}

myapp/lunchmap/templates/lunchmap/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
  <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
        <style>body {padding-top: 80px;}</style>
    <title>Lunchmap</title>
</head>
<body>
<nav class='navbar navbar-expand-sm navbar-dark bg-dark fixed-top'>
            <a class='navbar-brand' href='{% url "lunchmap:index" %}'>Lunchmap</a>
        </nav>
         <div class='container'>
           {% block content %}
           {% endblock %}
         </div>
</body>
</html>

myapp/lunchmap/templates/lunchmap/shop_confirm_delete.html
{% extends 'layout.html' %}
{% block content %}

<h1>お店情報の削除</h1>
<p>'{{object.name}}'を削除しますか？</p>
<form action='' method='post'>{% csrf_token %}
    {{ form.as_p }}
    <button type='submit' class='submit delete'>削除</button>
</form>
<div>
    <a href='JavaScript:history.back()'>&lt; 戻る</a>
</div>

{% endblock %}

myapp/lunchmap/templates/lunchmap/shop_detail.html
{% extends 'layout.html' %}
{% block content %}
<h1>{{shop.name}}</h1>
<div>
    <p>{{shop.category.namte}}</p>
    <p>{{shop.address}}</p>
</div>
<iframe id="map"  src='https://www.google.com/maps/embed/v1/place?key=AIzaSyCJBgcuCowQa5-V8owXaUCHhUNBN8bfMfU&amp;q={{ shop.address }}'
    width='100%'
    height='320'
    frameborder='0'></iframe>
<div>
    <a href="{% url 'lunchmap:index' %}">一覧</a>|
    {% if request.user.id == object.author_id%}
    <a href="{% url 'lunchmap:update' shop.pk %}">編集</a>|
    <a href="{% url 'lunchmap:delete' shop.pk %}">削除</a>
    {% endif %}
</div>
{% endblock %}

myapp/lunchmap/templates/lunchmap/shop_form.html
{% extends 'layout.html' %}
{% block content %}

<h1>お店情報の{{ object|yesno:'更新,作成'}}</h1>

<form action='' method='post'>{% csrf_token %}
    {{ form.as_p }}
    <button type='submit' class='submit'>{{ object|yesno:'更新,作成'}}</button>
</form>
<div>
    <a href='JavaScript:history.back()'>&lt; 戻る</a>
</div>

{% endblock %}

myapp/lunchmap/templates/lunchmap/shop_list.html
{% extends 'layout.html' %}
{% block content %}
<h1>お店一覧</h1>
<table class="table table-striped table-hover">
    <tr>
        <th>カテゴリ</th><th>店名</th><th>住所</th>
    </tr>
    {%for shop in object_list %}
    <tr>
        <td>{{shop.category.name}}</td>
        <td><a href="{% url 'lunchmap:detail' shop.pk %}">{{shop.name}}</a></td>
        <td> {{shop.address}}</td>
    </tr>
    {% endfor %}
</table>
{% if user.is_authenticated %}
<div>
    <a href="{% url 'lunchmap:create' %}">新しいお店</a>
</div>
{% endif %}
{% endblock %}

myapp/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
  <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
        <style>body {padding-top: 80px;}</style>
    <title>Lunchmap</title>
</head>
<body>
<nav class='navbar navbar-expand-sm navbar-dark bg-dark fixed-top'>
            <a class='navbar-brand' href='{% url "lunchmap:index" %}'>Lunchmap</a>
    <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item">
            <span class="navbar-text">{{user}} - </span>
        </li>
        <li class="nav-item">
            <a href="{% url 'logout' %}" class="logout nav-link">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a href="{% url 'login' %}" class="login nav-link">Login</a>
        </li>
                <li class="nav-item">
            <a href="{% url 'accounts:signup' %}" class="signup nav-link">SignUp</a>
        </li>

        {% endif %}
    </ul>
        </nav>
         <div class='container'>
           {% block content %}
           {% endblock %}
         </div>
</body>
</html>